name: Run ShellCheck

on:
  push:
    branches:
      - '*'  # Run on all branches
  pull_request:
    branches:
      - '*'  # Run on all branches

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck

    - name: Run ShellCheck
      run: |
        # Find all shell scripts and run shellcheck
        find . -name "*.sh" -print0 | xargs -0 shellcheck

